apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app.name}}-service
spec:
  selector:
    app: {{.Values.app.name}}-pod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: {{.Values.app.image.port}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app.name}}-mysql-service
spec:
  selector:
    app: {{.Values.app.name}}-mysql-pod
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app.name}}-redis-service
spec:
  selector:
    app: {{.Values.app.name}}-redis-pod
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
