# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
app:
  name: api
  replicas: 1
  image:
    repository: api-node
    pullPolicy: Never
    tag: "latest"
    port: 3000
    command: ["/app/run.sh"]
  requestsMemory: "200Mi"
  requestsCpu: "100m"
  limitsMemory: "1Gi"
  limitsCpu: "500m"
  environment:

mysql:
  image:
    repository: mysql
    tag: latest
  rootPassword: "root"
  database: "api-test"
  requestsMemory:
  requestsCpu:
  limitsMemory:
  limitsCpu:
  extraEnvironment:
    

redis:
  image:
    repository: redis
    tag: alpine
  requestsMemory:
  requestsCpu:
  limitsMemory:
  limitsCpu:
  extraEnvironment:
    

ingress:
  enabled: true
  host: "api.local"
