# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
app:
  name: api
  replicas: 1
  image:
    repository: api-node
    pullPolicy: Never
    tag: "latest"
    port: 3000
    command: ["/app/run.sh"]
  requestsMemory: "200Mi"
  requestsCpu: "100m"
  limitsMemory: "1Gi"
  limitsCpu: "500m"
  environment:

mysql:
  image:
    repository: mysql
    tag: latest
  password:
    fromSecret: false
    value: "root"
    secretName: app-secrets
    secretKey: MYSQL_PASSWORD
  database: "api-test"
  requestsMemory: "1Gi"
  requestsCpu: "300m"
  limitsMemory: "2Gi"
  limitsCpu: "500m"
  extraEnvironment:
    

redis:
  image:
    repository: redis
    tag: alpine
  requestsMemory: "200Mi"
  requestsCpu: "100m"
  limitsMemory: "400Mi"
  limitsCpu: "200m"
  extraEnvironment:
    

ingress:
  enabled: true
  host: "api.local"
